/*
Console API

       The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI.       If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know.       <br /><br />       <b>Authorization</b>       <br />       All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys)       <br /><br />       <b>Rate Limiting</b>       <br />       Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>.       <br /><br />       <b>Keyboard Search</b>       <br />       Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.       

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntityPropertySourceDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityPropertySourceDto{}

// EntityPropertySourceDto struct for EntityPropertySourceDto
type EntityPropertySourceDto struct {
	// Unique identifier for the entity property source.
	Name string `json:"name"`
	// Detailed context and purpose of the entity property source.
	Description string `json:"description"`
	// Tags for categorization and search.
	Tags []string `json:"tags"`
	// SQL query defining the data source.
	Sql string `json:"sql"`
	// Optional column name for timestamp.
	TimestampColumn *string `json:"timestampColumn,omitempty"`
	// Indicates if the timestamp is treated as a day.
	TimestampAsDay *bool `json:"timestampAsDay,omitempty"`
	// Mappings of Statsig units to their columns.
	IdTypeMapping []EntityPropertySourceDtoIdTypeMappingInner `json:"idTypeMapping"`
	// Specifies if the source can only be edited via the Console API.
	IsReadOnly *bool `json:"isReadOnly,omitempty"`
}

type _EntityPropertySourceDto EntityPropertySourceDto

// NewEntityPropertySourceDto instantiates a new EntityPropertySourceDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityPropertySourceDto(name string, description string, tags []string, sql string, idTypeMapping []EntityPropertySourceDtoIdTypeMappingInner) *EntityPropertySourceDto {
	this := EntityPropertySourceDto{}
	this.Name = name
	this.Description = description
	this.Tags = tags
	this.Sql = sql
	this.IdTypeMapping = idTypeMapping
	return &this
}

// NewEntityPropertySourceDtoWithDefaults instantiates a new EntityPropertySourceDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityPropertySourceDtoWithDefaults() *EntityPropertySourceDto {
	this := EntityPropertySourceDto{}
	return &this
}

// GetName returns the Name field value
func (o *EntityPropertySourceDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EntityPropertySourceDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EntityPropertySourceDto) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *EntityPropertySourceDto) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *EntityPropertySourceDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *EntityPropertySourceDto) SetDescription(v string) {
	o.Description = v
}

// GetTags returns the Tags field value
func (o *EntityPropertySourceDto) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *EntityPropertySourceDto) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *EntityPropertySourceDto) SetTags(v []string) {
	o.Tags = v
}

// GetSql returns the Sql field value
func (o *EntityPropertySourceDto) GetSql() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sql
}

// GetSqlOk returns a tuple with the Sql field value
// and a boolean to check if the value has been set.
func (o *EntityPropertySourceDto) GetSqlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sql, true
}

// SetSql sets field value
func (o *EntityPropertySourceDto) SetSql(v string) {
	o.Sql = v
}

// GetTimestampColumn returns the TimestampColumn field value if set, zero value otherwise.
func (o *EntityPropertySourceDto) GetTimestampColumn() string {
	if o == nil || IsNil(o.TimestampColumn) {
		var ret string
		return ret
	}
	return *o.TimestampColumn
}

// GetTimestampColumnOk returns a tuple with the TimestampColumn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityPropertySourceDto) GetTimestampColumnOk() (*string, bool) {
	if o == nil || IsNil(o.TimestampColumn) {
		return nil, false
	}
	return o.TimestampColumn, true
}

// HasTimestampColumn returns a boolean if a field has been set.
func (o *EntityPropertySourceDto) HasTimestampColumn() bool {
	if o != nil && !IsNil(o.TimestampColumn) {
		return true
	}

	return false
}

// SetTimestampColumn gets a reference to the given string and assigns it to the TimestampColumn field.
func (o *EntityPropertySourceDto) SetTimestampColumn(v string) {
	o.TimestampColumn = &v
}

// GetTimestampAsDay returns the TimestampAsDay field value if set, zero value otherwise.
func (o *EntityPropertySourceDto) GetTimestampAsDay() bool {
	if o == nil || IsNil(o.TimestampAsDay) {
		var ret bool
		return ret
	}
	return *o.TimestampAsDay
}

// GetTimestampAsDayOk returns a tuple with the TimestampAsDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityPropertySourceDto) GetTimestampAsDayOk() (*bool, bool) {
	if o == nil || IsNil(o.TimestampAsDay) {
		return nil, false
	}
	return o.TimestampAsDay, true
}

// HasTimestampAsDay returns a boolean if a field has been set.
func (o *EntityPropertySourceDto) HasTimestampAsDay() bool {
	if o != nil && !IsNil(o.TimestampAsDay) {
		return true
	}

	return false
}

// SetTimestampAsDay gets a reference to the given bool and assigns it to the TimestampAsDay field.
func (o *EntityPropertySourceDto) SetTimestampAsDay(v bool) {
	o.TimestampAsDay = &v
}

// GetIdTypeMapping returns the IdTypeMapping field value
func (o *EntityPropertySourceDto) GetIdTypeMapping() []EntityPropertySourceDtoIdTypeMappingInner {
	if o == nil {
		var ret []EntityPropertySourceDtoIdTypeMappingInner
		return ret
	}

	return o.IdTypeMapping
}

// GetIdTypeMappingOk returns a tuple with the IdTypeMapping field value
// and a boolean to check if the value has been set.
func (o *EntityPropertySourceDto) GetIdTypeMappingOk() ([]EntityPropertySourceDtoIdTypeMappingInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.IdTypeMapping, true
}

// SetIdTypeMapping sets field value
func (o *EntityPropertySourceDto) SetIdTypeMapping(v []EntityPropertySourceDtoIdTypeMappingInner) {
	o.IdTypeMapping = v
}

// GetIsReadOnly returns the IsReadOnly field value if set, zero value otherwise.
func (o *EntityPropertySourceDto) GetIsReadOnly() bool {
	if o == nil || IsNil(o.IsReadOnly) {
		var ret bool
		return ret
	}
	return *o.IsReadOnly
}

// GetIsReadOnlyOk returns a tuple with the IsReadOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntityPropertySourceDto) GetIsReadOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.IsReadOnly) {
		return nil, false
	}
	return o.IsReadOnly, true
}

// HasIsReadOnly returns a boolean if a field has been set.
func (o *EntityPropertySourceDto) HasIsReadOnly() bool {
	if o != nil && !IsNil(o.IsReadOnly) {
		return true
	}

	return false
}

// SetIsReadOnly gets a reference to the given bool and assigns it to the IsReadOnly field.
func (o *EntityPropertySourceDto) SetIsReadOnly(v bool) {
	o.IsReadOnly = &v
}

func (o EntityPropertySourceDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityPropertySourceDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["tags"] = o.Tags
	toSerialize["sql"] = o.Sql
	if !IsNil(o.TimestampColumn) {
		toSerialize["timestampColumn"] = o.TimestampColumn
	}
	if !IsNil(o.TimestampAsDay) {
		toSerialize["timestampAsDay"] = o.TimestampAsDay
	}
	toSerialize["idTypeMapping"] = o.IdTypeMapping
	if !IsNil(o.IsReadOnly) {
		toSerialize["isReadOnly"] = o.IsReadOnly
	}
	return toSerialize, nil
}

func (o *EntityPropertySourceDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
		"tags",
		"sql",
		"idTypeMapping",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityPropertySourceDto := _EntityPropertySourceDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntityPropertySourceDto)

	if err != nil {
		return err
	}

	*o = EntityPropertySourceDto(varEntityPropertySourceDto)

	return err
}

type NullableEntityPropertySourceDto struct {
	value *EntityPropertySourceDto
	isSet bool
}

func (v NullableEntityPropertySourceDto) Get() *EntityPropertySourceDto {
	return v.value
}

func (v *NullableEntityPropertySourceDto) Set(val *EntityPropertySourceDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityPropertySourceDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityPropertySourceDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityPropertySourceDto(val *EntityPropertySourceDto) *NullableEntityPropertySourceDto {
	return &NullableEntityPropertySourceDto{value: val, isSet: true}
}

func (v NullableEntityPropertySourceDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityPropertySourceDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


