/*
Console API

       The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI.       If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know.       <br /><br />       <b>Authorization</b>       <br />       All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys)       <br /><br />       <b>Rate Limiting</b>       <br />       Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>.       <br /><br />       <b>Keyboard Search</b>       <br />       Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.       

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReportDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportDto{}

// ReportDto struct for ReportDto
type ReportDto struct {
	// URL to the report
	Url string `json:"url"`
}

type _ReportDto ReportDto

// NewReportDto instantiates a new ReportDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportDto(url string) *ReportDto {
	this := ReportDto{}
	this.Url = url
	return &this
}

// NewReportDtoWithDefaults instantiates a new ReportDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportDtoWithDefaults() *ReportDto {
	this := ReportDto{}
	return &this
}

// GetUrl returns the Url field value
func (o *ReportDto) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ReportDto) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ReportDto) SetUrl(v string) {
	o.Url = v
}

func (o ReportDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *ReportDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReportDto := _ReportDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReportDto)

	if err != nil {
		return err
	}

	*o = ReportDto(varReportDto)

	return err
}

type NullableReportDto struct {
	value *ReportDto
	isSet bool
}

func (v NullableReportDto) Get() *ReportDto {
	return v.value
}

func (v *NullableReportDto) Set(val *ReportDto) {
	v.value = val
	v.isSet = true
}

func (v NullableReportDto) IsSet() bool {
	return v.isSet
}

func (v *NullableReportDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportDto(val *ReportDto) *NullableReportDto {
	return &NullableReportDto{value: val, isSet: true}
}

func (v NullableReportDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


