/*
Console API

       The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI.       If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know.       <br /><br />       <b>Authorization</b>       <br />       All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys)       <br /><br />       <b>Rate Limiting</b>       <br />       Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>.       <br /><br />       <b>Keyboard Search</b>       <br />       Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.       

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// LayerContractDtoParametersInnerDefaultValueOneOfInner - struct for LayerContractDtoParametersInnerDefaultValueOneOfInner
type LayerContractDtoParametersInnerDefaultValueOneOfInner struct {
	Bool *bool
	Float32 *float32
	MapmapOfStringAny *map[string]interface{}
	String *string
}

// boolAsLayerContractDtoParametersInnerDefaultValueOneOfInner is a convenience function that returns bool wrapped in LayerContractDtoParametersInnerDefaultValueOneOfInner
func BoolAsLayerContractDtoParametersInnerDefaultValueOneOfInner(v *bool) LayerContractDtoParametersInnerDefaultValueOneOfInner {
	return LayerContractDtoParametersInnerDefaultValueOneOfInner{
		Bool: v,
	}
}

// float32AsLayerContractDtoParametersInnerDefaultValueOneOfInner is a convenience function that returns float32 wrapped in LayerContractDtoParametersInnerDefaultValueOneOfInner
func Float32AsLayerContractDtoParametersInnerDefaultValueOneOfInner(v *float32) LayerContractDtoParametersInnerDefaultValueOneOfInner {
	return LayerContractDtoParametersInnerDefaultValueOneOfInner{
		Float32: v,
	}
}

// map[string]interface{}AsLayerContractDtoParametersInnerDefaultValueOneOfInner is a convenience function that returns map[string]interface{} wrapped in LayerContractDtoParametersInnerDefaultValueOneOfInner
func MapmapOfStringAnyAsLayerContractDtoParametersInnerDefaultValueOneOfInner(v *map[string]interface{}) LayerContractDtoParametersInnerDefaultValueOneOfInner {
	return LayerContractDtoParametersInnerDefaultValueOneOfInner{
		MapmapOfStringAny: v,
	}
}

// stringAsLayerContractDtoParametersInnerDefaultValueOneOfInner is a convenience function that returns string wrapped in LayerContractDtoParametersInnerDefaultValueOneOfInner
func StringAsLayerContractDtoParametersInnerDefaultValueOneOfInner(v *string) LayerContractDtoParametersInnerDefaultValueOneOfInner {
	return LayerContractDtoParametersInnerDefaultValueOneOfInner{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *LayerContractDtoParametersInnerDefaultValueOneOfInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal data into Float32
	err = newStrictDecoder(data).Decode(&dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			if err = validator.Validate(dst.Float32); err != nil {
				dst.Float32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil
		dst.Float32 = nil
		dst.MapmapOfStringAny = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(LayerContractDtoParametersInnerDefaultValueOneOfInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(LayerContractDtoParametersInnerDefaultValueOneOfInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src LayerContractDtoParametersInnerDefaultValueOneOfInner) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *LayerContractDtoParametersInnerDefaultValueOneOfInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	if obj.Float32 != nil {
		return obj.Float32
	}

	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableLayerContractDtoParametersInnerDefaultValueOneOfInner struct {
	value *LayerContractDtoParametersInnerDefaultValueOneOfInner
	isSet bool
}

func (v NullableLayerContractDtoParametersInnerDefaultValueOneOfInner) Get() *LayerContractDtoParametersInnerDefaultValueOneOfInner {
	return v.value
}

func (v *NullableLayerContractDtoParametersInnerDefaultValueOneOfInner) Set(val *LayerContractDtoParametersInnerDefaultValueOneOfInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLayerContractDtoParametersInnerDefaultValueOneOfInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLayerContractDtoParametersInnerDefaultValueOneOfInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLayerContractDtoParametersInnerDefaultValueOneOfInner(val *LayerContractDtoParametersInnerDefaultValueOneOfInner) *NullableLayerContractDtoParametersInnerDefaultValueOneOfInner {
	return &NullableLayerContractDtoParametersInnerDefaultValueOneOfInner{value: val, isSet: true}
}

func (v NullableLayerContractDtoParametersInnerDefaultValueOneOfInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLayerContractDtoParametersInnerDefaultValueOneOfInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


