/*
Console API

       The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI.       If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know.       <br /><br />       <b>Authorization</b>       <br />       All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys)       <br /><br />       <b>Rate Limiting</b>       <br />       Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>.       <br /><br />       <b>Keyboard Search</b>       <br />       Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.       

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HoldoutPartialUpdateContractDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HoldoutPartialUpdateContractDto{}

// HoldoutPartialUpdateContractDto struct for HoldoutPartialUpdateContractDto
type HoldoutPartialUpdateContractDto struct {
	// enable or disable the holdout
	IsEnabled *bool `json:"isEnabled,omitempty"`
	// brief summary of what the holdout is being used for
	Description *string `json:"description,omitempty"`
	// percentage of users between 0-10% to pass through the holdout
	PassPercentage *float32 `json:"passPercentage,omitempty"`
	// an array of gateIDs which this holdout is applied to
	GateIDs []string `json:"gateIDs,omitempty"`
	// an array of experimentIDs which this holdout is applied to
	ExperimentIDs []string `json:"experimentIDs,omitempty"`
	// an array of layerIDs which this holdout is applied to
	LayerIDs []string `json:"layerIDs,omitempty"`
	// whether the holdout is being applied to all new gates
	IsGlobal *bool `json:"isGlobal,omitempty"`
	// the gateID that the holdout is targeting
	TargetingGateID *nil `json:"targetingGateID,omitempty"`
}

// NewHoldoutPartialUpdateContractDto instantiates a new HoldoutPartialUpdateContractDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHoldoutPartialUpdateContractDto() *HoldoutPartialUpdateContractDto {
	this := HoldoutPartialUpdateContractDto{}
	return &this
}

// NewHoldoutPartialUpdateContractDtoWithDefaults instantiates a new HoldoutPartialUpdateContractDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHoldoutPartialUpdateContractDtoWithDefaults() *HoldoutPartialUpdateContractDto {
	this := HoldoutPartialUpdateContractDto{}
	return &this
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *HoldoutPartialUpdateContractDto) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HoldoutPartialUpdateContractDto) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *HoldoutPartialUpdateContractDto) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *HoldoutPartialUpdateContractDto) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *HoldoutPartialUpdateContractDto) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HoldoutPartialUpdateContractDto) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *HoldoutPartialUpdateContractDto) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *HoldoutPartialUpdateContractDto) SetDescription(v string) {
	o.Description = &v
}

// GetPassPercentage returns the PassPercentage field value if set, zero value otherwise.
func (o *HoldoutPartialUpdateContractDto) GetPassPercentage() float32 {
	if o == nil || IsNil(o.PassPercentage) {
		var ret float32
		return ret
	}
	return *o.PassPercentage
}

// GetPassPercentageOk returns a tuple with the PassPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HoldoutPartialUpdateContractDto) GetPassPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.PassPercentage) {
		return nil, false
	}
	return o.PassPercentage, true
}

// HasPassPercentage returns a boolean if a field has been set.
func (o *HoldoutPartialUpdateContractDto) HasPassPercentage() bool {
	if o != nil && !IsNil(o.PassPercentage) {
		return true
	}

	return false
}

// SetPassPercentage gets a reference to the given float32 and assigns it to the PassPercentage field.
func (o *HoldoutPartialUpdateContractDto) SetPassPercentage(v float32) {
	o.PassPercentage = &v
}

// GetGateIDs returns the GateIDs field value if set, zero value otherwise.
func (o *HoldoutPartialUpdateContractDto) GetGateIDs() []string {
	if o == nil || IsNil(o.GateIDs) {
		var ret []string
		return ret
	}
	return o.GateIDs
}

// GetGateIDsOk returns a tuple with the GateIDs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HoldoutPartialUpdateContractDto) GetGateIDsOk() ([]string, bool) {
	if o == nil || IsNil(o.GateIDs) {
		return nil, false
	}
	return o.GateIDs, true
}

// HasGateIDs returns a boolean if a field has been set.
func (o *HoldoutPartialUpdateContractDto) HasGateIDs() bool {
	if o != nil && !IsNil(o.GateIDs) {
		return true
	}

	return false
}

// SetGateIDs gets a reference to the given []string and assigns it to the GateIDs field.
func (o *HoldoutPartialUpdateContractDto) SetGateIDs(v []string) {
	o.GateIDs = v
}

// GetExperimentIDs returns the ExperimentIDs field value if set, zero value otherwise.
func (o *HoldoutPartialUpdateContractDto) GetExperimentIDs() []string {
	if o == nil || IsNil(o.ExperimentIDs) {
		var ret []string
		return ret
	}
	return o.ExperimentIDs
}

// GetExperimentIDsOk returns a tuple with the ExperimentIDs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HoldoutPartialUpdateContractDto) GetExperimentIDsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExperimentIDs) {
		return nil, false
	}
	return o.ExperimentIDs, true
}

// HasExperimentIDs returns a boolean if a field has been set.
func (o *HoldoutPartialUpdateContractDto) HasExperimentIDs() bool {
	if o != nil && !IsNil(o.ExperimentIDs) {
		return true
	}

	return false
}

// SetExperimentIDs gets a reference to the given []string and assigns it to the ExperimentIDs field.
func (o *HoldoutPartialUpdateContractDto) SetExperimentIDs(v []string) {
	o.ExperimentIDs = v
}

// GetLayerIDs returns the LayerIDs field value if set, zero value otherwise.
func (o *HoldoutPartialUpdateContractDto) GetLayerIDs() []string {
	if o == nil || IsNil(o.LayerIDs) {
		var ret []string
		return ret
	}
	return o.LayerIDs
}

// GetLayerIDsOk returns a tuple with the LayerIDs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HoldoutPartialUpdateContractDto) GetLayerIDsOk() ([]string, bool) {
	if o == nil || IsNil(o.LayerIDs) {
		return nil, false
	}
	return o.LayerIDs, true
}

// HasLayerIDs returns a boolean if a field has been set.
func (o *HoldoutPartialUpdateContractDto) HasLayerIDs() bool {
	if o != nil && !IsNil(o.LayerIDs) {
		return true
	}

	return false
}

// SetLayerIDs gets a reference to the given []string and assigns it to the LayerIDs field.
func (o *HoldoutPartialUpdateContractDto) SetLayerIDs(v []string) {
	o.LayerIDs = v
}

// GetIsGlobal returns the IsGlobal field value if set, zero value otherwise.
func (o *HoldoutPartialUpdateContractDto) GetIsGlobal() bool {
	if o == nil || IsNil(o.IsGlobal) {
		var ret bool
		return ret
	}
	return *o.IsGlobal
}

// GetIsGlobalOk returns a tuple with the IsGlobal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HoldoutPartialUpdateContractDto) GetIsGlobalOk() (*bool, bool) {
	if o == nil || IsNil(o.IsGlobal) {
		return nil, false
	}
	return o.IsGlobal, true
}

// HasIsGlobal returns a boolean if a field has been set.
func (o *HoldoutPartialUpdateContractDto) HasIsGlobal() bool {
	if o != nil && !IsNil(o.IsGlobal) {
		return true
	}

	return false
}

// SetIsGlobal gets a reference to the given bool and assigns it to the IsGlobal field.
func (o *HoldoutPartialUpdateContractDto) SetIsGlobal(v bool) {
	o.IsGlobal = &v
}

// GetTargetingGateID returns the TargetingGateID field value if set, zero value otherwise.
func (o *HoldoutPartialUpdateContractDto) GetTargetingGateID() nil {
	if o == nil || IsNil(o.TargetingGateID) {
		var ret nil
		return ret
	}
	return *o.TargetingGateID
}

// GetTargetingGateIDOk returns a tuple with the TargetingGateID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HoldoutPartialUpdateContractDto) GetTargetingGateIDOk() (*nil, bool) {
	if o == nil || IsNil(o.TargetingGateID) {
		return nil, false
	}
	return o.TargetingGateID, true
}

// HasTargetingGateID returns a boolean if a field has been set.
func (o *HoldoutPartialUpdateContractDto) HasTargetingGateID() bool {
	if o != nil && !IsNil(o.TargetingGateID) {
		return true
	}

	return false
}

// SetTargetingGateID gets a reference to the given nil and assigns it to the TargetingGateID field.
func (o *HoldoutPartialUpdateContractDto) SetTargetingGateID(v nil) {
	o.TargetingGateID = &v
}

func (o HoldoutPartialUpdateContractDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HoldoutPartialUpdateContractDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsEnabled) {
		toSerialize["isEnabled"] = o.IsEnabled
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.PassPercentage) {
		toSerialize["passPercentage"] = o.PassPercentage
	}
	if !IsNil(o.GateIDs) {
		toSerialize["gateIDs"] = o.GateIDs
	}
	if !IsNil(o.ExperimentIDs) {
		toSerialize["experimentIDs"] = o.ExperimentIDs
	}
	if !IsNil(o.LayerIDs) {
		toSerialize["layerIDs"] = o.LayerIDs
	}
	if !IsNil(o.IsGlobal) {
		toSerialize["isGlobal"] = o.IsGlobal
	}
	if !IsNil(o.TargetingGateID) {
		toSerialize["targetingGateID"] = o.TargetingGateID
	}
	return toSerialize, nil
}

type NullableHoldoutPartialUpdateContractDto struct {
	value *HoldoutPartialUpdateContractDto
	isSet bool
}

func (v NullableHoldoutPartialUpdateContractDto) Get() *HoldoutPartialUpdateContractDto {
	return v.value
}

func (v *NullableHoldoutPartialUpdateContractDto) Set(val *HoldoutPartialUpdateContractDto) {
	v.value = val
	v.isSet = true
}

func (v NullableHoldoutPartialUpdateContractDto) IsSet() bool {
	return v.isSet
}

func (v *NullableHoldoutPartialUpdateContractDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHoldoutPartialUpdateContractDto(val *HoldoutPartialUpdateContractDto) *NullableHoldoutPartialUpdateContractDto {
	return &NullableHoldoutPartialUpdateContractDto{value: val, isSet: true}
}

func (v NullableHoldoutPartialUpdateContractDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHoldoutPartialUpdateContractDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


