/*
Console API

       The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI.       If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know.       <br /><br />       <b>Authorization</b>       <br />       All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys)       <br /><br />       <b>Rate Limiting</b>       <br />       Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>.       <br /><br />       <b>Keyboard Search</b>       <br />       Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.       

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SegmentCreateContractDtoRulesInnerConditionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SegmentCreateContractDtoRulesInnerConditionsInner{}

// SegmentCreateContractDtoRulesInnerConditionsInner struct for SegmentCreateContractDtoRulesInnerConditionsInner
type SegmentCreateContractDtoRulesInnerConditionsInner struct {
	TargetValue NullableDynamicConfigDtoRulesInnerConditionsInnerTargetValue `json:"targetValue,omitempty"`
	Operator *string `json:"operator,omitempty"`
	Field *nil `json:"field,omitempty"`
	CustomID *nil `json:"customID,omitempty"`
	Type string `json:"type"`
}

type _SegmentCreateContractDtoRulesInnerConditionsInner SegmentCreateContractDtoRulesInnerConditionsInner

// NewSegmentCreateContractDtoRulesInnerConditionsInner instantiates a new SegmentCreateContractDtoRulesInnerConditionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSegmentCreateContractDtoRulesInnerConditionsInner(type_ string) *SegmentCreateContractDtoRulesInnerConditionsInner {
	this := SegmentCreateContractDtoRulesInnerConditionsInner{}
	this.Type = type_
	return &this
}

// NewSegmentCreateContractDtoRulesInnerConditionsInnerWithDefaults instantiates a new SegmentCreateContractDtoRulesInnerConditionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSegmentCreateContractDtoRulesInnerConditionsInnerWithDefaults() *SegmentCreateContractDtoRulesInnerConditionsInner {
	this := SegmentCreateContractDtoRulesInnerConditionsInner{}
	return &this
}

// GetTargetValue returns the TargetValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) GetTargetValue() DynamicConfigDtoRulesInnerConditionsInnerTargetValue {
	if o == nil || IsNil(o.TargetValue.Get()) {
		var ret DynamicConfigDtoRulesInnerConditionsInnerTargetValue
		return ret
	}
	return *o.TargetValue.Get()
}

// GetTargetValueOk returns a tuple with the TargetValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) GetTargetValueOk() (*DynamicConfigDtoRulesInnerConditionsInnerTargetValue, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetValue.Get(), o.TargetValue.IsSet()
}

// HasTargetValue returns a boolean if a field has been set.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) HasTargetValue() bool {
	if o != nil && o.TargetValue.IsSet() {
		return true
	}

	return false
}

// SetTargetValue gets a reference to the given NullableDynamicConfigDtoRulesInnerConditionsInnerTargetValue and assigns it to the TargetValue field.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) SetTargetValue(v DynamicConfigDtoRulesInnerConditionsInnerTargetValue) {
	o.TargetValue.Set(&v)
}
// SetTargetValueNil sets the value for TargetValue to be an explicit nil
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) SetTargetValueNil() {
	o.TargetValue.Set(nil)
}

// UnsetTargetValue ensures that no value is present for TargetValue, not even an explicit nil
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) UnsetTargetValue() {
	o.TargetValue.Unset()
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) SetOperator(v string) {
	o.Operator = &v
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) GetField() nil {
	if o == nil || IsNil(o.Field) {
		var ret nil
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) GetFieldOk() (*nil, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given nil and assigns it to the Field field.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) SetField(v nil) {
	o.Field = &v
}

// GetCustomID returns the CustomID field value if set, zero value otherwise.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) GetCustomID() nil {
	if o == nil || IsNil(o.CustomID) {
		var ret nil
		return ret
	}
	return *o.CustomID
}

// GetCustomIDOk returns a tuple with the CustomID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) GetCustomIDOk() (*nil, bool) {
	if o == nil || IsNil(o.CustomID) {
		return nil, false
	}
	return o.CustomID, true
}

// HasCustomID returns a boolean if a field has been set.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) HasCustomID() bool {
	if o != nil && !IsNil(o.CustomID) {
		return true
	}

	return false
}

// SetCustomID gets a reference to the given nil and assigns it to the CustomID field.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) SetCustomID(v nil) {
	o.CustomID = &v
}

// GetType returns the Type field value
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SegmentCreateContractDtoRulesInnerConditionsInner) SetType(v string) {
	o.Type = v
}

func (o SegmentCreateContractDtoRulesInnerConditionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SegmentCreateContractDtoRulesInnerConditionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.TargetValue.IsSet() {
		toSerialize["targetValue"] = o.TargetValue.Get()
	}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.CustomID) {
		toSerialize["customID"] = o.CustomID
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *SegmentCreateContractDtoRulesInnerConditionsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSegmentCreateContractDtoRulesInnerConditionsInner := _SegmentCreateContractDtoRulesInnerConditionsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSegmentCreateContractDtoRulesInnerConditionsInner)

	if err != nil {
		return err
	}

	*o = SegmentCreateContractDtoRulesInnerConditionsInner(varSegmentCreateContractDtoRulesInnerConditionsInner)

	return err
}

type NullableSegmentCreateContractDtoRulesInnerConditionsInner struct {
	value *SegmentCreateContractDtoRulesInnerConditionsInner
	isSet bool
}

func (v NullableSegmentCreateContractDtoRulesInnerConditionsInner) Get() *SegmentCreateContractDtoRulesInnerConditionsInner {
	return v.value
}

func (v *NullableSegmentCreateContractDtoRulesInnerConditionsInner) Set(val *SegmentCreateContractDtoRulesInnerConditionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSegmentCreateContractDtoRulesInnerConditionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSegmentCreateContractDtoRulesInnerConditionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSegmentCreateContractDtoRulesInnerConditionsInner(val *SegmentCreateContractDtoRulesInnerConditionsInner) *NullableSegmentCreateContractDtoRulesInnerConditionsInner {
	return &NullableSegmentCreateContractDtoRulesInnerConditionsInner{value: val, isSet: true}
}

func (v NullableSegmentCreateContractDtoRulesInnerConditionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSegmentCreateContractDtoRulesInnerConditionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


