/*
Console API

       The \"Console API\" is the CRUD API for performing the actions offered on console.statsig.com without needing to go through the web UI.       If you have any feature requests, drop on in to our [slack channel](https://www.statsig.com/slack) and let us know.       <br /><br />       <b>Authorization</b>       <br />       All requests must include the **STATSIG-API-KEY** field in the header. The value should be a **Console API Key** which can be created in the Project Settings on [console.statsig.com/api_keys](https://console.statsig.com/api_keys)       <br /><br />       <b>Rate Limiting</b>       <br />       Requests to the Console API are limited to <code>~ 100reqs / 10secs and ~ 900reqs / 15 mins</code>.       <br /><br />       <b>Keyboard Search</b>       <br />       Use <code>Ctrl/Cmd + K</code> to search for specific endpoints.       

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AutotuneCreateDtoVariantsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutotuneCreateDtoVariantsInner{}

// AutotuneCreateDtoVariantsInner An array of Variant objects
type AutotuneCreateDtoVariantsInner struct {
	// Variant name
	Name string `json:"name"`
	// Variant JSON data
	Json interface{} `json:"json"`
}

type _AutotuneCreateDtoVariantsInner AutotuneCreateDtoVariantsInner

// NewAutotuneCreateDtoVariantsInner instantiates a new AutotuneCreateDtoVariantsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutotuneCreateDtoVariantsInner(name string, json interface{}) *AutotuneCreateDtoVariantsInner {
	this := AutotuneCreateDtoVariantsInner{}
	this.Name = name
	this.Json = json
	return &this
}

// NewAutotuneCreateDtoVariantsInnerWithDefaults instantiates a new AutotuneCreateDtoVariantsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutotuneCreateDtoVariantsInnerWithDefaults() *AutotuneCreateDtoVariantsInner {
	this := AutotuneCreateDtoVariantsInner{}
	return &this
}

// GetName returns the Name field value
func (o *AutotuneCreateDtoVariantsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AutotuneCreateDtoVariantsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AutotuneCreateDtoVariantsInner) SetName(v string) {
	o.Name = v
}

// GetJson returns the Json field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *AutotuneCreateDtoVariantsInner) GetJson() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Json
}

// GetJsonOk returns a tuple with the Json field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AutotuneCreateDtoVariantsInner) GetJsonOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Json) {
		return nil, false
	}
	return &o.Json, true
}

// SetJson sets field value
func (o *AutotuneCreateDtoVariantsInner) SetJson(v interface{}) {
	o.Json = v
}

func (o AutotuneCreateDtoVariantsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutotuneCreateDtoVariantsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Json != nil {
		toSerialize["json"] = o.Json
	}
	return toSerialize, nil
}

func (o *AutotuneCreateDtoVariantsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"json",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAutotuneCreateDtoVariantsInner := _AutotuneCreateDtoVariantsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAutotuneCreateDtoVariantsInner)

	if err != nil {
		return err
	}

	*o = AutotuneCreateDtoVariantsInner(varAutotuneCreateDtoVariantsInner)

	return err
}

type NullableAutotuneCreateDtoVariantsInner struct {
	value *AutotuneCreateDtoVariantsInner
	isSet bool
}

func (v NullableAutotuneCreateDtoVariantsInner) Get() *AutotuneCreateDtoVariantsInner {
	return v.value
}

func (v *NullableAutotuneCreateDtoVariantsInner) Set(val *AutotuneCreateDtoVariantsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAutotuneCreateDtoVariantsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAutotuneCreateDtoVariantsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutotuneCreateDtoVariantsInner(val *AutotuneCreateDtoVariantsInner) *NullableAutotuneCreateDtoVariantsInner {
	return &NullableAutotuneCreateDtoVariantsInner{value: val, isSet: true}
}

func (v NullableAutotuneCreateDtoVariantsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutotuneCreateDtoVariantsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


