"feature":
  - head-branch: ["feature/*", "feat/*"]
"fix":
  - head-branch: ["fix/*", "bug/*"]
"chore":
  - head-branch: ["chore/*", "docs/*", "refactor/*"]
"breaking-change":
  - head-branch: ["breaking/*", "major/*"]
