name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels: ["feature"]
  - title: "🐛 Bug Fixes"
    labels: ["fix"]
  - title: "🧰 Maintenance"
    labels: ["chore"]
change-template: "-- [[#$NUMBER]($URL)] $TITLE by @$AUTHOR"
version-resolver:
  major:
    labels: ["breaking-change"]
  minor:
    labels: ["feature"]
  patch:
    labels: ["fix", "chore"]
  default: patch
prerelease-identifier: "alpha"
template: |
  ## Changes

  $CHANGES
