name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement"]
  - title: "🐛 Bug Fixes"
    labels: ["bug", "fix"]
  - title: "🧰 Maintenance"
    labels: ["chore", "refactor"]
change-template: "-- [#[$NUMBER]($URL)] $TITLE by @$AUTHOR"
version-resolver:
  major:
    labels: ["breaking-change"]
  minor:
    labels: ["feature", "enhancement"]
  patch:
    labels: ["bug", "fix", "chore", "refactor"]
  default: patch
prerelease-identifier: "alpha"
template: |
  ## Changes

  $CHANGES
autolabeler:
  - label: "feature"
    branch:
      - feature/*
      - feat/*
  - label: "fix"
    branch:
      - fix/*
      - bug/*
  - label: "chore"
    branch:
      - chore/*
      - docs/*
      - refactor/*
  - label: "breaking-change"
    branch:
      - breaking/*
      - major/*
