name: Auto Labeler

on:
  pull_request:
    branches:
      - main

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
