name: Draft GitHub Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  call-draft-release:
    uses: useless-solutions/.github/.github/workflows/release-draft.yml@main
