name: 🚔 CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  call-ci:
    uses: useless-solutions/.github/.github/workflows/pr.yml@main
    with:
      GO_VERSION: "1.24"
